// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvZsJ4YJnmzX3srtR0n2R5s7QHKiZgU4',
    appId: '1:1005404362108:web:0635d3bd31d0b9698080f9',
    messagingSenderId: '1005404362108',
    projectId: 'chat-b6fe7',
    authDomain: 'chat-b6fe7.firebaseapp.com',
    storageBucket: 'chat-b6fe7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtwFb_HodCq3RoSCIEpmcR7mdca3qW4A',
    appId: '1:1005404362108:android:95464897e43d8e1c8080f9',
    messagingSenderId: '1005404362108',
    projectId: 'chat-b6fe7',
    storageBucket: 'chat-b6fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHh6_r_ndRhQLbHQHPQj2Us3rltcXKO9M',
    appId: '1:1005404362108:ios:fcc2f7378d7d73358080f9',
    messagingSenderId: '1005404362108',
    projectId: 'chat-b6fe7',
    storageBucket: 'chat-b6fe7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHh6_r_ndRhQLbHQHPQj2Us3rltcXKO9M',
    appId: '1:1005404362108:ios:fcc2f7378d7d73358080f9',
    messagingSenderId: '1005404362108',
    projectId: 'chat-b6fe7',
    storageBucket: 'chat-b6fe7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvZsJ4YJnmzX3srtR0n2R5s7QHKiZgU4',
    appId: '1:1005404362108:web:c3511cc8c4710ae58080f9',
    messagingSenderId: '1005404362108',
    projectId: 'chat-b6fe7',
    authDomain: 'chat-b6fe7.firebaseapp.com',
    storageBucket: 'chat-b6fe7.firebasestorage.app',
  );
}
